// Generated by CoffeeScript 1.9.3

/*
  NODE MODULES
 */

(function() {
  var call, check, flag, flagger, matchKey,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    slice = [].slice;

  flagger = require('flagger')();


  /*
    SETUP
   */

  flag = flagger.print || flagger.p;


  /*
    FUNCTIONS
   */

  matchKey = function(keys) {
    var i, key, len;
    if (typeof keys === 'string' && indexOf.call(flag, keys) >= 0) {
      return true;
    }
    for (i = 0, len = keys.length; i < len; i++) {
      key = keys[i];
      if (indexOf.call(flag, key) >= 0) {
        return true;
      }
    }
  };

  check = function(keyString) {
    return flag && (flag.length === 0 || matchKey(keyString));
  };

  call = function() {
    var func, keyString, toPrint;
    func = arguments[0], keyString = arguments[1], toPrint = 3 <= arguments.length ? slice.call(arguments, 2) : [];
    if (check(keyString)) {
      return console[func].apply(console, toPrint);
    }
  };


  /*
    EXPORT
   */

  module.exports = {
    log: function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return call.apply(null, ['log'].concat(slice.call(args)));
    }
  };

}).call(this);
