// Generated by CoffeeScript 1.9.3

/*
  NODE MODULES
 */

(function() {
  var check, flag, flagger, matchKey,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    slice = [].slice;

  flagger = require('flagger')();


  /*
    SETUP
   */

  flag = flagger.print || flagger.p;


  /*
    FUNCTIONS
   */

  matchKey = function(keys) {
    var i, key, len;
    if (typeof keys === 'string' && indexOf.call(flag, keys) >= 0) {
      return true;
    }
    for (i = 0, len = keys.length; i < len; i++) {
      key = keys[i];
      if (indexOf.call(flag, key) >= 0) {
        return true;
      }
    }
  };

  check = function(keyString) {
    return flag && (flag.length === 0 || matchKey(keyString));
  };


  /*
    EXPORT
   */

  module.exports = {
    log: function() {
      var keyString, toPrint;
      keyString = arguments[0], toPrint = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      if (check(keyString)) {
        return console.log.apply(console, toPrint);
      }
    }
  };

}).call(this);
